version: "3.8"
services:
  gateway:
    image: hela/gateway-server:0.0.1-SNAPSHOT
    ports:
      - 8080:8080

  discovery:
    image: hela/discovery-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761

  config:
    image: hela/config-server:0.0.1-SNAPSHOT
    volumes:
      - ./config:/var/config
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery

  users:
    image: hela/user-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config

  content_database:
    image: cassandra:4.0
    volumes:
      - ./volumes/cassandra:/opt/cassandra
    ports:
      - 9042:9042

  content:
    image: hela/content-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
      - content_database
