version: "3"
services:
  discovery:
    image: hela/discovery-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761

  config:
    image: hela/configuration-server:0.0.1-SNAPSHOT
    volumes:
      - ./config:/var/config
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - discovery
    ports:
      - 8888:8888

  users:
    image: hela/user-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config

  content:
    image: hela/content-service:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
