server:
  port: 8002

spring:
  application:
    name: content-service

  data:
    cassandra:
      keyspace-name: fictitiousstockexchange
      port: 9042
      contact-points: content_database
      local-datacenter: datacenter1
      entity-base-package: contentservice.models
